### ISSUE TITLE
onBlur and onFocus events

### ISSUE THREAD

**Issue by JorisM** [slamdata/purescript-ace-halogen#2]
Is it possible to add an option to query the `onBlur` and `onFocus` events of the ace editor? 

such as: https://github.com/slamdata/purescript-ace/blob/master/example/src/Main.purs#L48-L49

thanks for the library and your time!

**Comment by cryogenian** [comment]
Hello! 

Unfortunately it's impossible now. Current implementation has no such query and since it has bug with handling multiple editors it's not worth to implement it before #3. Though, after update it will be complicated because editors are constructed on every init/quit.

**Comment by cryogenian** [comment]
Ok, now it's possible :) 
In example if you have component that have only one child and this child is `Ace.Halogen.Component` you can make request to get `Editor`

``` purescript
editor <- query slot $ request GetEditor
```

And then you can subscribe to `Editor.onBlur/onFocus`

**Comment by JorisM** [comment]
Wow thanks a bunch for this!
I will update and try to implement it and report back.
