### ISSUE TITLE
Updating to recent purescript?

### ISSUE THREAD

**Issue by chrisdone** [slamdata/purescript-ace-halogen#27]
Any plans for this? Just curious. Deciding whether to use CodeMirror or Ace.

**Comment by garyb** [comment]
I think we will be doing so at some point, but it's not on the immediate radar. This library doesn't have much to it really so would be easy to do, but [`purescript-ace`](https://github.com/slamdata/purescript-ace) itself has a lot of stuff in it, and is probably way behind the latest Ace too, so will take a bit more work.

From your post figuring out event sources I guess you decided to go with CodeMirror anyway!

**Comment by chrisdone** [comment]
Right, sorry for opening so many issues everywhere, haha! It turns out doing a little CodeMirror component has been a good forcing function to learn more of the Halogen API surface area, so yeah that's good! :ok_hand:

**Comment by garyb** [comment]
Oh, no problem! Constructive issues are always welcome :smile:
