### ISSUE TITLE
Cannot read property 'addCompleter' of undefined

### ISSUE THREAD

**Issue by archaeron** [slamdata/purescript-ace-halogen#5]
I get en error when trying to use the package

```
Uncaught TypeError: Cannot read property 'addCompleter' of undefined
```

I'm using:

```
        H.slot' cpAce AceSlot \_ ->
            { component :
                Ace.aceComponent
                    (\_ ->
                        pure unit)
                    Nothing
            , initialState :
                initialAceState
            }
```

I'll inverstigate a bit, but maybe you have an idea already :)

**Comment by archaeron** [comment]
sorry, was missing `ace/ext/language_tools`.

**Comment by garyb** [comment]
That's good to know though, is it something we should mention in the `README`?

**Comment by archaeron** [comment]
What would really help is a small, working example in the repo that shows most of the things you can do. That also imports every dependency.

my code looks like this at the moment:

```
H.slot' cpAce AceSlot \_ ->
            { component :
                Ace.aceComponent
                    (\editor -> liftEff $ do
                        session <- Editor.getSession editor
                        Session.setMode "ace/mode/yaml" session
                        Editor.setValue initialText Nothing editor
                        pure unit
                    )
                    Nothing
            , initialState :
                { key : Nothing, editor : Nothing }
            }
```

my index.html imports:

```
bower_components/ace-builds/src-min/ace.js
bower_components/ace-builds/src-min/mode-yaml.js
bower_components/ace-builds/src-min/ext-language_tools.js
```

what I can't figure out is how and where to use `onBlur`
so maybe a small contained example that has an editor where you can input yaml and the yaml is displayed as-is in a div somewhere next to it.

I could set up an example, if I leave out the `onBlur`.

**Comment by archaeron** [comment]
@garyb maybe something like this?
https://github.com/archaeron/purescript-ace-halogen/commit/a812c146a9e2b5823082d581a7dffd2b20310d1e

**Comment by garyb** [comment]
@archaeron an example would be great, could you make a PR for it please? I ran into this exact problem myself the other day and forgot entirely about this issue until going back through my email... oops.

**Comment by archaeron** [comment]
@garyb no worries :)

Here is the PR:
https://github.com/slamdata/purescript-ace-halogen/pull/8
