### ISSUE TITLE
Autocomplete setup causing issues

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-ace-halogen#7]
@cryogenian something in here https://github.com/slamdata/purescript-ace-halogen/blob/dc13bbcda3d708d283fc1779c9d8144099c30ce6/src/Ace/Halogen/Component.purs#L186-L189 blocks further progress (no statements after the lifted `do` execute) so I suspect maybe there's an uncaught exception getting lost based on something happening in there.

Maybe there's something about the Ace setup in `new-halogen` that's causing this alternatively - missing a js include we need to have this work or something?

Could you take a look please? Thanks!

**Comment by cryogenian** [comment]
Yeah, it's missing file in `new-halogen`. I'm making pr with ace update for `new-halogen` and then update `autocomplete` branch.

**Comment by cryogenian** [comment]
This is fixed by adding `ext-language_tools.js` to `notebook.html`.
